### ISSUE TITLE
Semicolon in the function CliqueExpansionModularity

### ISSUE THREAD

**Issue by mcontisc** [nveldt/HyperModularity.jl#4]
Hello :) I am trying to use your code and I noticed there is a semicolon after the gamma argument in `line 51` of the file `graph_louvain.jl`: 
```function CliqueExpansionModularity(H::hypergraph,gamma::Float64=1.0;weighted::Bool=true,randflag::Bool=false,binary::Bool=false,clusterpenalty::Float64=0.0,maxits::Int64=10000)```

This does not allow calling the function with the arguments after gamma.

**Comment by PhilChodrow** [comment]
Thank you for this! Can you send us a pull request?

- Phil

Phil Chodrow || www.philchodrow.com || he/him/his

**Comment by nveldt** [comment]
Thanks for using the code @mcontisc, but hang on a sec before pushing anything, as this is not a bug but it just the way Julia functions work :)

The semicolon is purposeful. Everything after the semicolon is viewed as an optional parameter, and the syntax just needs to be a little different if you are going to set these parameters. You just need to write out what the parameter is, and then set it. For example, if you want to set "weighted" to false instead of true, you have to do this:

CliqueExpansionModularity(H,gamma; weighted = true)

instead of trying to do

CliqueExpansionModularity(H,gamma, true)

The benefit of this is that if you only want to set one specific optional parameter, you just set that without having to set the other parameters that come "before it" in the way it's written. E.g., you could call

CliqueExpansionModularity(H,gamma; maxits = 2000)

without worrying about setting weighted, randflag, or clusterpenalty.

**Comment by mcontisc** [comment]
Thank @nveldt for the clarification :) I do appreciate your timely reply and exhaustive answer.
I just got confused from some demos I was looking at where there was no semicolon. 

Sorry for the inconvenience and thanks again!
